name: Bug Report Updater
on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  update-bug-report:
    name: Bug Report Updater
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    if: contains(github.actor, 'github-actions') == false
    steps:
      - name: Checkout code
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          fetch-depth: 0
          ref: ${{ github.event.repository.default_branch }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update laravel version
        id: laravel
        uses: ShaMan123/gha-populate-form-version@c289e3d22bff63c3935c1880da1cc6bdf4b16c23 # v2.0.2
        with:
          dropdown: _laravel_version
          package: laravel/laravel
          registry: github
          semver: ">=6.0"
          form: .github/ISSUE_TEMPLATE/bug_report.yml
          commit_message: "chore(): update laravel version in bug report template"
          dry_run: no-push

      - name: Update Node version
        id: node
        uses: ShaMan123/gha-populate-form-version@c289e3d22bff63c3935c1880da1cc6bdf4b16c23 # v2.0.2
        with:
          dropdown: _node_version
          package: node
          semver: ">=16.14.0"
          form: .github/ISSUE_TEMPLATE/bug_report.yml
          commit_message: "chore(): update node version in bug report template"
          dry_run: no-push

      - name: Commit & PR
        uses: peter-evans/create-pull-request@284f54f989303d2699d373481a0cfa13ad5a6666 # v5.0.1
        with:
          commit-message: "chore(): update bug report template [skip ci]"
          add-paths: .github/ISSUE_TEMPLATE/bug_report.yml
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: workflow/update-bug-report-template
          base: main
          delete-branch: true
          title: "chore(): update bug report template"
          body: |
            Automated update to `.github/ISSUE_TEMPLATE/bug_report.yml`
