name: Contributors List
on:
  workflow_dispatch:
  
  schedule:
    - cron: "0 3 */2 * *"

jobs:
  contributors:
    runs-on: ubuntu-latest
    name: Update contributors list

    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
        with:
          fetch-depth: 0
          ref: ${{ github.event.repository.default_branch }}
          
      - name: Update Contributors
        uses: wow-actions/contributors-list@b9e91f91a51a55460fdcae64daad0cb8122cdd53 # v1.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          svgPath: .github/assets/CONTRIBUTORS.svg
          round: true
          noCommit: true
      
      - name: Commit & PR
        uses: peter-evans/create-pull-request@38e0b6e68b4c852a5500a94740f0e535e0d7ba54 # v4.2.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore(): update contributors-list'
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: workflow/update-contributors-list
          base: main
          delete-branch: true
          body: |
            Automated update to `.github/assets/CONTRIBUTORS.svg`

