name: Contributors List Updater

on:
  workflow_dispatch:

  schedule:
    - cron: "0 3 */2 * *"

permissions:
  contents: read

jobs:
  sync-contributors:
    name: Contributors List Updater
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
        with:
          fetch-depth: 0
          ref: ${{ github.event.repository.default_branch }}

      - name: Update contributors list
        uses: wow-actions/contributors-list@242b53835016268d20e79eeff6f42193c02be8c8 # v1.2.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          svgPath: .github/assets/CONTRIBUTORS.svg
          round: true
          includeBots: false
          excludeUsers: "step-security-bot"
          noCommit: true

      - name: Commit & PR
        uses: peter-evans/create-pull-request@38e0b6e68b4c852a5500a94740f0e535e0d7ba54 # v4.2.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          add-paths: .github/assets/CONTRIBUTORS.svg
          commit-message: "chore(): update contributors-list"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: workflow/update-contributors-list
          base: main
          delete-branch: true
          title: "chore(): update contributors-list"
          body: |
            Automated update to `.github/assets/CONTRIBUTORS.svg`
