name: Pull Request Labeler

on: [pull_request_target]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  pr-labeler:
    name: Pull Request Labeler
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Apply PR Labels
        uses: actions/labeler@0967ca812e7fdc8f5f71402a1b486d5bd061fe20 # v4.2.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          # https://github.com/actions/labeler/issues/442#issuecomment-1297359481
          sync-labels: ""
