name: Pull Request Labeler

on: [pull_request_target]

jobs:
  label-pull-request:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      
    steps:
      - uses: actions/labeler@ba790c862c380240c6d5e7427be5ace9a05c754b # v4.0.3
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
