name: Pull Request Labeler

on: [pull_request_target]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  pr-labeler:
    name: Pull Request Labeler
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Apply PR Labels
        uses: actions/labeler@0776a679364a9a16110aac8d0f40f5e11009e327 # v4.0.4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          # https://github.com/actions/labeler/issues/442#issuecomment-1297359481
          sync-labels: ""
