name: Split Laravel Package

on:
  push:
    branches:
      - main
    paths:
      - 'packages/laravel/**'
    tags:
      - '@wreathe-js/laravel@*'

jobs:
  packages_split:
    name: Split Laravel Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
        with:
          fetch-depth: 0

      - if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        name: Update package repository
        uses: alphpaca/monoplus-split-action@249ebd74a6eec4481d412fe0747a43527445c439 # 2022.1-alpha6
        with:
          package_path: 'packages/laravel'
          personal_access_token: ${{ secrets.PAT }}
          git_username: 'wreathe-js'
          git_email: 'github@wreathe.dev'
          repository_owner: 'wreathe-js'
          repository_name: 'laravel'

      - if: ${{ startsWith(github.ref, 'refs/tags/') }}
        name: Extract tag
        id: extract_tag
        run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}

      - if: ${{ startsWith(github.ref, 'refs/tags/') }}
        name: Create package tag
        uses: alphpaca/monoplus-split-action@249ebd74a6eec4481d412fe0747a43527445c439 # 2022.1-alpha6

        with:
          package_path: 'packages/laravel'
          personal_access_token: ${{ secrets.PAT }}
          git_username: 'wreathe-js'
          git_email: 'github@wreathe.dev'
          repository_owner: 'wreathe-js'
          repository_name: 'laravel'
          tag: ${{ steps.extract_tag.outputs.TAG }}
