name: Sync Labels

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  sync-labels:
    name: Sync Labels
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Checkout code
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0

      - name: Apply Labels
        uses: EndBug/label-sync@da00f2c11fdb78e4fae44adac2fdd713778ea3e8 # v2.3.2
        with:
          config-file: .github/labels.yml
          request-token: ${{ secrets.GITHUB_TOKEN }}
          delete-other-labels: true
