name: Sync Labels
on:
  workflow_dispatch:

jobs:
  sync:
    name: Run EndBug/label-sync
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      - uses: EndBug/label-sync@da00f2c11fdb78e4fae44adac2fdd713778ea3e8 # v2.3.2
        with:
          config-file: .github/labels.yml
          request-token: ${{ secrets.YOUR_OWN_SECRET }}
          delete-other-labels: true
